version: '3'

services:
  app:
    build:
      args:
        user: martin
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: minierp
    container_name: minierp-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    ports:
      - "9001:9000"
  nginx:
    image: nginx:alpine
    container_name: minierp-server
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
networks:
  default:
    external: true
    name: nginx-network